title: Sustainable Thinking
description: >
  **Sustainable Thinking** Julian Saliani's Blog
copyright: Julian Saliani
sass:
  sass_dir: assets/sass
url:
disqus_shortname: stratajekylldemo
facebook_username:
twitter_username: "#"
linkedin_username: "#"
instagram_username:
pinterest_username:
flickr_username:
github_username:  "jsaliani92"
feed_icon: rss
email: "#"
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
