title: Julian Saliani
description: >
  **I am Strata**, a super simple
  responsive site template freebie
  crafted by [HTML5 UP](http://html5up.net).
copyright: Julian Saliani
sass:
  sass_dir: assets/sass
url:
disqus_shortname: stratajekylldemo
facebook_username:
twitter_username: "#"
linkedin_username: "#"
instagram_username:
pinterest_username:
flickr_username:
github_username:  "jsaliani92"
feed_icon: rss
email: "#"
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
